version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: natural
    versions:
    - 2.4.5
    - 3.0.0
    - 3.0.1
    - 4.0.0
    - 4.0.2
    - 4.0.3
    - 4.0.4
    - 5.0.1
    - 5.0.2
